name: "🚀 Feature Request"
description: "Suggest an idea for this project"
labels: ["feature", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        **Issue title (above):** _Provide a clear and concise summary of the feature, e.g., "Add user profile page"_

  - type: textarea
    id: problem_description
    attributes:
      label: "Problem Description"
      description: "Is your feature request related to a problem? Please describe the problem this feature would solve."
      placeholder: "e.g., I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "Describe the solution you'd like. Be as specific as possible."
      placeholder: "e.g., Implement a new page at /profile where users can..."
    validations:
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: "Alternatives Considered (Optional)"
      description: "Describe any alternative solutions or features you've considered."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context (Optional)"
      description: "Add any other context, mockups, or screenshots about the feature request here."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature to you?"
      options:
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true

  - type: input
    id: related_issue
    attributes:
      label: "Related Issue (Optional)"
      description: "Link any related issues (e.g., bugs this feature would resolve, other related features)"
      placeholder: "#123"
    validations:
      required: false
