name: Spell Check

on: [push, pull_request]

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: cspell
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: |
            **/*.md
            **/*.txt
          # The cspell action defaults to English.
          # For specific dictionaries or configurations,
          # you can add a cspell.json configuration file.
          # Example for explicitly setting English language (though usually not needed):
          # cspell_command: "cspell --language-id en \"**/*.md\" \"**/*.txt\""
