name: Gitleaks Scan

on: [push, pull_request]

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to scan full history
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional: for reporting to GitHub Security tab if configured
          # GITLEAKS_CONFIG: .gitleaks.toml # Optional: if you have a custom Gitleaks config file
